# Generated by Django 4.0.6 on 2022-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('image', models.ImageField(upload_to='past_speakers/')),
                ('designation', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='past_speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('image', models.ImageField(upload_to='past_speakers/')),
                ('designation', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
