# Generated by Django 4.0.6 on 2022-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('image', models.ImageField(upload_to='past_speakers/')),
                ('designation', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('image', models.ImageField(upload_to='sponsors/')),
                ('url', models.URLField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='sponsors_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sponsors', models.ManyToManyField(to='sponsors.sponsors')),
            ],
        ),
    ]
