# Generated by Django 4.0.6 on 2022-07-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='summits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('data', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('cost', models.CharField(max_length=12)),
                ('data', models.JSONField(blank=True, null=True)),
                ('features', models.ManyToManyField(to='event.feature')),
                ('not_available', models.ManyToManyField(related_name='not_available', to='event.feature')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('subtitle', models.CharField(blank=True, max_length=240, null=True)),
                ('From', models.TimeField(null=True)),
                ('To', models.TimeField(null=True)),
                ('location', models.TextField(null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(default='', editable=False)),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.summits')),
            ],
        ),
        migrations.CreateModel(
            name='event_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField()),
                ('events', models.ManyToManyField(to='event.events')),
            ],
        ),
    ]
