# Generated by Django 4.0.6 on 2022-07-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cost',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
