# Generated by Django 4.0.6 on 2022-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_ticket_cost_alter_ticket_not_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='', editable=False, null=True),
        ),
    ]
