# Generated by Django 4.0.6 on 2022-07-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('tshirt_size', models.CharField(max_length=8)),
                ('linkedin', models.TextField()),
                ('social_links', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=240)),
                ('college_name', models.CharField(blank=True, max_length=360, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('tshirt_size', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=240)),
                ('college_name', models.CharField(blank=True, max_length=360, null=True)),
                ('company_name', models.CharField(max_length=360)),
                ('linkedin', models.TextField()),
                ('social_links', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('showcasing_product', models.BooleanField(default=False)),
                ('hiring_interns', models.BooleanField(default=False)),
                ('hiring_professionals', models.BooleanField(default=False)),
                ('cu_passout', models.BooleanField(default=False)),
                ('pitchbook', models.FileField(blank=True, null=True, upload_to='startup/pitchbook/')),
                ('office_location', models.TextField(blank=True, null=True)),
                ('total_employees', models.CharField(blank=True, max_length=26, null=True)),
                ('describe_one_sentence', models.TextField()),
                ('core_problem', models.TextField()),
                ('use_case', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('business_model', models.TextField(blank=True, null=True)),
                ('have_revenue', models.BooleanField()),
                ('biggest_competetiors', models.TextField()),
                ('why_unique', models.TextField()),
                ('is_proprietary', models.BooleanField(default=False)),
                ('raise_capital', models.TextField()),
                ('video_url', models.TextField(blank=True, null=True)),
                ('incubator_program', models.TextField(blank=True, null=True)),
                ('company_category', models.CharField(max_length=120)),
                ('industry', models.CharField(max_length=120)),
                ('where_you_know', models.CharField(max_length=120)),
                ('team_representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.participants')),
            ],
        ),
    ]
