# Generated by Django 4.0.6 on 2022-07-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_attende_participants_startup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='biggest_competetiors',
        ),
        migrations.AddField(
            model_name='attende',
            name='where_you_know',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='biggest_competitors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='where_you_know',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
