# Generated by Django 4.0.6 on 2022-07-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_ticket_cost_alter_ticket_not_available'),
        ('registration', '0003_remove_startup_biggest_competetiors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=60)),
                ('attende', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='registration.attende')),
                ('startup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='registration.startup')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(default='', max_length=17, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.users')),
            ],
        ),
    ]
