# Generated by Django 4.0.6 on 2022-07-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_users_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='attende',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.attende'),
        ),
        migrations.AlterField(
            model_name='users',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.startup'),
        ),
    ]
